### ISSUE TITLE
KeyPressDuration in EventInfo

### ISSUE THREAD

**Issue by phalasz** [quasilyte/ebitengine-input#32]
Would be great to have key press duration made available in the EventInfo object.
Would make it easier to handle checks on how long a key was pressed for. Maybe only adding it in for `PressedActionInfo`

If there is interest I'm happy to draft a PR with some proposed changes for discussion.

**Comment by quasilyte** [comment]
This feature can be useful indeed.
I wonder if it can be implemented efficiently.

**Comment by quasilyte** [comment]
Am I right that tick/frame based duration is good enough for your use case?
I was thinking about the time-based duration since Update has this information, but it would require more efforts from this library part (I'm almost sure the inpututil stores this information uses global-ish maps with mutexes, lol)

**Comment by phalasz** [comment]
Yeah, for me the tick based duration is good enough for now.
